export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/img1.jpg",
      price: 60,
      brand: " Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Lorem ipsum dndjh nzvgs  gszcvyk",
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/img1.jpg",
      price: 50,
      brand: " Nike",
      rating: 4.2,
      numReviews: 5,
      description: "Lorem ipsum dndjh nzvgs  gszcvyk",
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/img1.jpg",
      price: 70,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      description: "Lorem ipsum dndjh nzvgs  gszcvyk",
    },
    {
      _id: "4",
      name: "Best Pants",
      category: "Pants",
      image: "/images/img1.jpg",
      price: 70,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      description: "Lorem ipsum dndjh nzvgs  gszcvyk",
    },
  ],
};
